using System.Xml.Serialization;
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.573.
// 

namespace FlightDataBase
{
    /// <remarks/>
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class account
    {
        /// <remarks/>
        [XmlElement("user")]
        public accountUser[] user; //List of users

        /// <remarks/>
        [XmlAttribute()]
        public bool major; //whether it is  major

        /// <remarks/>
        [XmlAttribute()]
        public bool minor; //whether it is a minor
    }

    /// <remarks/>
    public class accountUser
    {
        /// <remarks/>
        public accountUserAllowAllStation allowAllStation; //the users allowed to operated all stations

        /// <remarks/>
        [XmlArrayItem("station", IsNullable = false)]
        public accountUserStation[] allowOperatingStation; //operation allowed stations 

        /// <remarks/>
        [XmlArrayItem("opactype", IsNullable = false)]
        public accountUserOpactype[] allowOperatingActype; //operation allowed Aircraft types

        /// <remarks/>
        [XmlAttribute()]
        public string username; //User Name

        /// <remarks/>
        [XmlAttribute()]
        public string password; //Password

        /// <remarks/>
        [XmlAttribute()]
        public int license; //the index of lisence

        /// <remarks/>
        [XmlAttribute()]
        public string work_at_station; //the station at which the user works

        /// <remarks/>
        [XmlAttribute()]
        public int authority; //the integer indicating authority

        /// <remarks/>
        [XmlAttribute()]
        public string fullname; //the user's full name

        /// <remarks/>
        [XmlAttribute()]
        public string description; //user description
    }

    /// <remarks/>
    public class accountUserAllowAllStation
    {
        /// <remarks/>
        [XmlAttribute()]
        public bool flag; //whether the account is allowed to operate all stations
    }

    /// <remarks/>
    public class accountUserOpactype
    {
        /// <remarks/>
        [XmlAttribute()]
        public string name; //Aircraft type name
    }

    /// <remarks/>
    public class accountUserStation
    {
        /// <remarks/>
        [XmlAttribute()]
        public string name; //station name
    }
}