using System;
using System.Xml.Serialization;
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.2032.
// 

namespace FlightDataBase
{
    /// <remarks/>
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class airinfo
    {
        /// <remarks/>
        [XmlElement("airline")]
        public airinfoAirline[] airline;

        /// <remarks/>
        [XmlAttribute()]
        public int major;

        /// <remarks/>
        [XmlAttribute()]
        public int minor;
    }

    /// <remarks/>
    public class airinfoAirline
    {
        /// <remarks/>
        [XmlElement("airtype")]
        public airinfoAirlineAirtype[] airtype;

        /// <remarks/>
        [XmlAttribute()]
        public string name;
    }

    /// <remarks/>
    public class airinfoAirlineAirtype
    {
        /// <remarks/>
        [XmlElement("aircode")]
        public airinfoAirlineAirtypeAircode[] aircode;

        /// <remarks/>
        [XmlAttribute()]
        public string name;

        /// <remarks/>
        [XmlAttribute()]
        public string opactype;

        /// <remarks/>
        [XmlAttribute()]
        public airinfoAirlineAirtypeCategory category;

        /// <remarks/>
        [XmlAttribute()]
        public string lif;
    }

    /// <remarks/>
    public class airinfoAirlineAirtypeAircode
    {
        /// <remarks/>
        [XmlAttribute()]
        public string name;

        /// <remarks/>
        [XmlAttribute()]
        public int bw;

        /// <remarks/>
        [XmlAttribute()]
        public Single bi;
    }

    /// <remarks/>
    public enum airinfoAirlineAirtypeCategory
    {
        /// <remarks/>
        Passenger,

        /// <remarks/>
        Freighter,
    }
}