using System;
using System.Xml.Serialization;
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.2032.
// 

namespace FlightDataBase
{
    /// <remarks/>
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class airlines
    {
        /// <remarks/>
        [XmlElement("airline")]
        public airlinesAirline[] airline;

        /// <remarks/>
        [XmlAttribute()]
        public bool major;

        /// <remarks/>
        [XmlAttribute()]
        public bool minor;
    }

    /// <remarks/>
    public class airlinesAirline
    {
        /// <remarks/>
        [XmlArrayItem("uld", IsNullable = false)]
        public airlinesAirlineUld[] uldInfo;

        /// <remarks/>
        [XmlArrayItem("shcInfo", IsNullable = false)]
        public airlinesAirlineShcInfo[] SpecialLoad;

        /// <remarks/>
        [XmlArrayItem("dginfo", IsNullable = false)]
        public airlinesAirlineDginfo[] prohibit;

        /// <remarks/>
        public airlinesAirlinePersonWeight PersonWeight;

        /// <remarks/>
        [XmlArrayItem("finfo", IsNullable = false)]
        public airlinesAirlineFinfo[] FuelDensity;

        /// <remarks/>
        [XmlArrayItem("station", IsNullable = false)]
        public airlinesAirlineStation[] telexInfo;

        /// <remarks/>
        [XmlAttribute()]
        public string name;
    }

    /// <remarks/>
    public class airlinesAirlineUld
    {
        /// <remarks/>
        [XmlElement("serialNo")]
        public airlinesAirlineUldSerialNo[] serialNo;

        /// <remarks/>
        [XmlAttribute()]
        public string type;

        /// <remarks/>
        [XmlAttribute()]
        public short mgw;

        /// <remarks/>
        [XmlAttribute()]
        public string dim;

        /// <remarks/>
        [XmlAttribute()]
        public bool iscontainer;

        /// <remarks/>
        [XmlAttribute()]
        public string baseCode;

        /// <remarks/>
        [XmlAttribute()]
        public string highCode;
    }

    /// <remarks/>
    public class airlinesAirlineUldSerialNo
    {
        /// <remarks/>
        [XmlAttribute()]
        public int min;

        /// <remarks/>
        [XmlAttribute()]
        public int max;

        /// <remarks/>
        [XmlAttribute()]
        public short tareWt;
    }

    /// <remarks/>
    public class airlinesAirlineStationFlightTypeFlightTinfoSite
    {
        /// <remarks/>
        [XmlAttribute()]
        public string sita;
    }

    /// <remarks/>
    public class airlinesAirlineStationFlightTypeFlightTinfo
    {
        /// <remarks/>
        [XmlElement("site")]
        public airlinesAirlineStationFlightTypeFlightTinfoSite[] site;

        /// <remarks/>
        [XmlAttribute()]
        public string telex;
    }

    /// <remarks/>
    public class airlinesAirlineStationFlightTypeFlight
    {
        /// <remarks/>
        [XmlElement("tinfo")]
        public airlinesAirlineStationFlightTypeFlightTinfo[] tinfo;

        /// <remarks/>
        [XmlAttribute()]
        public string name;
    }

    /// <remarks/>
    public class airlinesAirlineStationFlightType
    {
        /// <remarks/>
        [XmlElement("flight")]
        public airlinesAirlineStationFlightTypeFlight[] flight;

        /// <remarks/>
        [XmlAttribute()]
        public string name;

        /// <remarks/>
        [XmlAttribute()]
        public string dblsig;

        /// <remarks/>
        [XmlAttribute()]
        public string sender;
    }

    /// <remarks/>
    public class airlinesAirlineStation
    {
        /// <remarks/>
        [XmlElement("flightType")]
        public airlinesAirlineStationFlightType[] flightType;

        /// <remarks/>
        [XmlAttribute()]
        public string name;
    }

    /// <remarks/>
    public class airlinesAirlineFinfo
    {
        /// <remarks/>
        [XmlAttribute()]
        public string from;

        /// <remarks/>
        [XmlAttribute()]
        public Decimal density;
    }

    /// <remarks/>
    public class airlinesAirlinePersonWeightCrew
    {
        /// <remarks/>
        [XmlAttribute()]
        public SByte P;

        /// <remarks/>
        [XmlAttribute()]
        public SByte C;
    }

    /// <remarks/>
    public class airlinesAirlinePersonWeightPAX
    {
        /// <remarks/>
        [XmlAttribute()]
        public SByte M;

        /// <remarks/>
        [XmlAttribute()]
        public SByte F;

        /// <remarks/>
        [XmlAttribute()]
        public SByte C;

        /// <remarks/>
        [XmlAttribute()]
        public SByte I;
    }

    /// <remarks/>
    public class airlinesAirlinePersonWeight
    {
        /// <remarks/>
        public airlinesAirlinePersonWeightPAX PAX;

        /// <remarks/>
        public airlinesAirlinePersonWeightCrew Crew;
    }

    /// <remarks/>
    public class airlinesAirlineDginfo
    {
        /// <remarks/>
        [XmlAttribute()]
        public string sp1;

        /// <remarks/>
        [XmlAttribute()]
        public string sp2;

        /// <remarks/>
        [XmlAttribute()]
        public SByte type;
    }

    /// <remarks/>
    public class airlinesAirlineShcInfo
    {
        /// <remarks/>
        [XmlAttribute()]
        public string catg;

        /// <remarks/>
        [XmlAttribute()]
        public string shc;

        /// <remarks/>
        [XmlAttribute()]
        public bool notoc;

        /// <remarks/>
        [XmlAttribute()]
        public bool dg;
    }
}